backend:
  name: github
  repo: VG2992-Innov8/Cur8r  # your GitHub repo full name
  branch: main
  auth_scope: repo

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
