backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Site Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Page Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
